# Generated by Django 3.2.5 on 2021-07-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, height_field=300, upload_to='blog/images/'),
        ),
    ]
